#!/bin/bash
#
#skripti algus
echo -n "Sisesta reisijate arv bussis: "
read reisijate_arv
echo -n "Sisesta kohtade arv bussis: "
read kohtade_arv
t2idetud=`expr $reisijate_arv / $kohtade_arv`
maha=`expr $reisijate_arv % $kohtade_arv`

if [ $maha -gt 0 ]
then
bussid=$(( $t2idetud + 1 ))
else
bussid=$t2idetud
fi
echo -n "Kokku on vaja $bussid bussi
"
#skripti lõpp
