#!/bin/bash
#
#skripti algus
arvud="1 2 3 4 5 6 7 8 9 10"
summa=0
for arv in $arvud
do
if [ $(($arv % 2)) -eq 0 ]; then
summa=$(($summa + $arv))
echo  $summa
fi
done

echo -n "Paarisarvude summa 1-10 on : $summa 
"
#
#skripti lõpp
#
